default_language_version:
  python: python3.12
repos:
  - repo: local
    hooks:
      - id: ruff_format
        name: Ruff format
        entry: ruff format
        language: python
        types:
          - python
      - id: ruff
        name: Ruff
        entry: ruff check --fix --unsafe-fixes --preview
        language: python
        types:
          - python
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types:
          - python

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
