name: Format code
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  format:
    name: Format with ruff
    runs-on: [ self-hosted, small ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - run: poetry run ruff format .

      - run: poetry run ruff --fix --unsafe-fixes --preview --exit-zero .

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          fetch: false
          default_author: github_actions
          message: 'Backend: Auto format'
          add: '.'
